sudo: required
services:
    - docker

# before running tests
before_install:
    - docker build -t roopam527/docker-check-up -f Dockerfile.dev .

script:
    - docker run -e CI=true roopam527/docker-check-up npm run test


deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "projectx"
    env: "Projectx-env"
    bucket_name: "elasticbeanstalk-ap-south-1-073494628974"
    bucket_path: "projectx"
    on:
        branch: master 
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: "$AWS_SECRET_KEY"