sudo: required
services:
    - docker

# before running tests
before_install:
    - docker build -t roopam527/docker-check-up -f Dockerfile.dev .

script:
    - docker run -e CI=true roopam527/docker-check-up npm run test